package edu.aku.hassannaqvi.f4he_baseline.database


import edu.aku.hassannaqvi.f4he_baseline.contracts.TableContracts.*
import edu.aku.hassannaqvi.f4he_baseline.core.MainApp.PROJECT_NAME


object CreateTable {

    const val DATABASE_NAME = "$PROJECT_NAME.db"
    const val DATABASE_COPY = "${PROJECT_NAME}_copy.db"
    const val DATABASE_VERSION = 1

    const val SQL_CREATE_FORMS = ("CREATE TABLE "
            + FormsTable.TABLE_NAME + "("
            + FormsTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + FormsTable.COLUMN_PROJECT_NAME + " TEXT,"
            + FormsTable.COLUMN_UID + " TEXT,"
            + FormsTable.COLUMN_PSU_CODE + " TEXT,"
            + FormsTable.COLUMN_HHID + " TEXT,"
            + FormsTable.COLUMN_SNO + " TEXT,"
            + FormsTable.COLUMN_USERNAME + " TEXT,"
            + FormsTable.COLUMN_SYSDATE + " TEXT,"
            + FormsTable.COLUMN_ISTATUS + " TEXT,"
            + FormsTable.COLUMN_DEVICEID + " TEXT,"
            + FormsTable.COLUMN_DEVICETAGID + " TEXT,"
            + FormsTable.COLUMN_SYNCED + " TEXT,"
            + FormsTable.COLUMN_SYNCED_DATE + " TEXT,"
            + FormsTable.COLUMN_APPVERSION + " TEXT,"
            + FormsTable.COLUMN_SA1 + " TEXT,"
            + FormsTable.COLUMN_SB1 + " TEXT,"
            + FormsTable.COLUMN_SB2 + " TEXT,"
            + FormsTable.COLUMN_SB3 + " TEXT,"
            + FormsTable.COLUMN_SB41 + " TEXT,"
            + FormsTable.COLUMN_SB42 + " TEXT,"
            + FormsTable.COLUMN_SB5 + " TEXT,"
            + FormsTable.COLUMN_SB6 + " TEXT,"
            + FormsTable.COLUMN_SB7 + " TEXT,"
            + FormsTable.COLUMN_SC1 + " TEXT,"
            + FormsTable.COLUMN_SC2 + " TEXT,"
            + FormsTable.COLUMN_SC31 + " TEXT,"
            + FormsTable.COLUMN_SC32 + " TEXT,"
            + FormsTable.COLUMN_SC4 + " TEXT,"
            + FormsTable.COLUMN_SC5 + " TEXT,"
            + FormsTable.COLUMN_SD1 + " TEXT,"
            + FormsTable.COLUMN_SD2 + " TEXT,"
            + FormsTable.COLUMN_SD3 + " TEXT,"
            + FormsTable.COLUMN_SE1 + " TEXT,"
            + FormsTable.COLUMN_SE2 + " TEXT,"
            + FormsTable.COLUMN_SE3 + " TEXT,"
            + FormsTable.COLUMN_SE4 + " TEXT"
            + " );"
            )

    const val SQL_CREATE_FAMILYMEMBERS = ("CREATE TABLE "
            + FamilyMembersTable.TABLE_NAME + "("
            + FamilyMembersTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + FamilyMembersTable.COLUMN_PROJECT_NAME + " TEXT,"
            + FamilyMembersTable.COLUMN_UID + " TEXT,"
            + FamilyMembersTable.COLUMN_UUID + " TEXT,"
            + FamilyMembersTable.COLUMN_PSU_CODE + " TEXT,"
            + FamilyMembersTable.COLUMN_HHID + " TEXT,"
            + FamilyMembersTable.COLUMN_SNO + " TEXT,"
            + FamilyMembersTable.COLUMN_USERNAME + " TEXT,"
            + FamilyMembersTable.COLUMN_SYSDATE + " TEXT,"
            + FamilyMembersTable.COLUMN_INDEXED + " TEXT,"
            + FamilyMembersTable.COLUMN_ISTATUS + " TEXT,"
            + FamilyMembersTable.COLUMN_DEVICEID + " TEXT,"
            + FamilyMembersTable.COLUMN_DEVICETAGID + " TEXT,"
            + FamilyMembersTable.COLUMN_SYNCED + " TEXT,"
            + FamilyMembersTable.COLUMN_SYNCED_DATE + " TEXT,"
            + FamilyMembersTable.COLUMN_APPVERSION + " TEXT,"
            + FamilyMembersTable.COLUMN_SA2 + " TEXT"
            + " );"
            )

    const val SQL_CREATE_FORMB = ("CREATE TABLE "
            + FormBTable.TABLE_NAME + "("
            + FormBTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + FormBTable.COLUMN_PROJECT_NAME + " TEXT,"
            + FormBTable.COLUMN_UID + " TEXT,"
            + FormBTable.COLUMN_UUID + " TEXT,"
            + FormBTable.COLUMN_PSU_CODE + " TEXT,"
            + FormBTable.COLUMN_HHID + " TEXT,"
            + FormBTable.COLUMN_SNO + " TEXT,"
            + FormBTable.COLUMN_USERNAME + " TEXT,"
            + FormBTable.COLUMN_SYSDATE + " TEXT,"
            + FormBTable.COLUMN_ISTATUS + " TEXT,"
            + FormBTable.COLUMN_DEVICEID + " TEXT,"
            + FormBTable.COLUMN_DEVICETAGID + " TEXT,"
            + FormBTable.COLUMN_SYNCED + " TEXT,"
            + FormBTable.COLUMN_SYNCED_DATE + " TEXT,"
            + FormBTable.COLUMN_APPVERSION + " TEXT,"
            + FormBTable.COLUMN_SB1 + " TEXT,"
            + FormBTable.COLUMN_SB2 + " TEXT,"
            + FormBTable.COLUMN_SB3 + " TEXT,"
            + FormBTable.COLUMN_SB41 + " TEXT,"
            + FormBTable.COLUMN_SB42 + " TEXT,"
            + FormBTable.COLUMN_SB5 + " TEXT,"
            + FormBTable.COLUMN_SB6 + " TEXT,"
            + FormBTable.COLUMN_SB7 + " TEXT"
            + " );"
            )

/*    const val SQL_CREATE_FAMILY_MEMBERS = ("CREATE TABLE "
            + FamilyMembersTable.TABLE_NAME + "("
            + FamilyMembersTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + FamilyMembersTable.COLUMN_PROJECT_NAME + " TEXT,"
            + FamilyMembersTable.COLUMN_UID + " TEXT,"
            + FamilyMembersTable.COLUMN_UUID + " TEXT,"
            + FamilyMembersTable.COLUMN_EB_CODE + " TEXT,"
            + FamilyMembersTable.COLUMN_HHID + " TEXT,"
            + FamilyMembersTable.COLUMN_USERNAME + " TEXT,"
            + FamilyMembersTable.COLUMN_SYSDATE + " TEXT,"
            + FamilyMembersTable.COLUMN_INDEXED + " TEXT,"
            + FamilyMembersTable.COLUMN_ISTATUS + " TEXT,"
            + FamilyMembersTable.COLUMN_DEVICEID + " TEXT,"
            + FamilyMembersTable.COLUMN_DEVICETAGID + " TEXT,"
            + FamilyMembersTable.COLUMN_SYNCED + " TEXT,"
            + FamilyMembersTable.COLUMN_SYNCED_DATE + " TEXT,"
            + FamilyMembersTable.COLUMN_APPVERSION + " TEXT,"
            + FamilyMembersTable.COLUMN_SA2 + " TEXT"
            + " );"
            )*/


    const val SQL_CREATE_MWRA = ("CREATE TABLE "
            + MwraTable.TABLE_NAME + "("
            + MwraTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + MwraTable.COLUMN_PROJECT_NAME + " TEXT,"
            + MwraTable.COLUMN_UID + " TEXT,"
            + MwraTable.COLUMN_UUID + " TEXT,"
            + MwraTable.COLUMN_EB_CODE + " TEXT,"
            + MwraTable.COLUMN_HHID + " TEXT,"
            + MwraTable.COLUMN_USERNAME + " TEXT,"
            + MwraTable.COLUMN_SYSDATE + " TEXT,"
            + MwraTable.COLUMN_INDEXED + " TEXT,"
            + MwraTable.COLUMN_ISTATUS + " TEXT,"
            + MwraTable.COLUMN_DEVICEID + " TEXT,"
            + MwraTable.COLUMN_DEVICETAGID + " TEXT,"
            + MwraTable.COLUMN_SYNCED + " TEXT,"
            + MwraTable.COLUMN_SYNCED_DATE + " TEXT,"
            + MwraTable.COLUMN_APPVERSION + " TEXT,"
            + MwraTable.COLUMN_SB1 + " TEXT,"
            + MwraTable.COLUMN_SB2 + " TEXT,"
            + MwraTable.COLUMN_SB3 + " TEXT,"
            + MwraTable.COLUMN_SB41 + " TEXT,"
            + MwraTable.COLUMN_SB42 + " TEXT,"
            + MwraTable.COLUMN_SB5 + " TEXT,"
            + MwraTable.COLUMN_SB6 + " TEXT,"
            + MwraTable.COLUMN_SB7 + " TEXT,"
            + MwraTable.COLUMN_SD1 + " TEXT,"
            + MwraTable.COLUMN_SD2 + " TEXT,"
            + MwraTable.COLUMN_SD3 + " TEXT"
            + " );"
            )

    const val SQL_CREATE_PREGNANCY = ("CREATE TABLE "
            + Pregnancy_Table.TABLE_NAME + "("
            + Pregnancy_Table.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + Pregnancy_Table.COLUMN_PROJECT_NAME + " TEXT,"
            + Pregnancy_Table.COLUMN_UID + " TEXT,"
            + Pregnancy_Table.COLUMN_UUID + " TEXT,"
            + Pregnancy_Table.COLUMN_EB_CODE + " TEXT,"
            + Pregnancy_Table.COLUMN_HHID + " TEXT,"
            + Pregnancy_Table.COLUMN_USERNAME + " TEXT,"
            + Pregnancy_Table.COLUMN_SYSDATE + " TEXT,"
            + Pregnancy_Table.COLUMN_INDEXED + " TEXT,"
            + Pregnancy_Table.COLUMN_ISTATUS + " TEXT,"
            + Pregnancy_Table.COLUMN_DEVICEID + " TEXT,"
            + Pregnancy_Table.COLUMN_DEVICETAGID + " TEXT,"
            + Pregnancy_Table.COLUMN_SYNCED + " TEXT,"
            + Pregnancy_Table.COLUMN_SYNCED_DATE + " TEXT,"
            + Pregnancy_Table.COLUMN_APPVERSION + " TEXT,"
            + Pregnancy_Table.COLUMN_SB1 + " TEXT"

            + " );"
            )

    const val SQL_CREATE_ADOLESCENT = ("CREATE TABLE "
            + LateAdolescent_Table.TABLE_NAME + "("
            + LateAdolescent_Table.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + LateAdolescent_Table.COLUMN_PROJECT_NAME + " TEXT,"
            + LateAdolescent_Table.COLUMN_UID + " TEXT,"
            + LateAdolescent_Table.COLUMN_UUID + " TEXT,"
            + LateAdolescent_Table.COLUMN_EB_CODE + " TEXT,"
            + LateAdolescent_Table.COLUMN_HHID + " TEXT,"
            + LateAdolescent_Table.COLUMN_USERNAME + " TEXT,"
            + LateAdolescent_Table.COLUMN_SYSDATE + " TEXT,"
            + LateAdolescent_Table.COLUMN_INDEXED + " TEXT,"
            + LateAdolescent_Table.COLUMN_ISTATUS + " TEXT,"
            + LateAdolescent_Table.COLUMN_DEVICEID + " TEXT,"
            + LateAdolescent_Table.COLUMN_DEVICETAGID + " TEXT,"
            + LateAdolescent_Table.COLUMN_SYNCED + " TEXT,"
            + LateAdolescent_Table.COLUMN_SYNCED_DATE + " TEXT,"
            + LateAdolescent_Table.COLUMN_APPVERSION + " TEXT,"
            + LateAdolescent_Table.COLUMN_SE1 + " TEXT,"
            + LateAdolescent_Table.COLUMN_SE2 + " TEXT,"
            + LateAdolescent_Table.COLUMN_SE3 + " TEXT,"
            + LateAdolescent_Table.COLUMN_SE4 + " TEXT"

            + " );"
            )

    const val SQL_CREATE_CHILD = ("CREATE TABLE "
            + Child_Table.TABLE_NAME + "("
            + Child_Table.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + Child_Table.COLUMN_PROJECT_NAME + " TEXT,"
            + Child_Table.COLUMN_UID + " TEXT,"
            + Child_Table.COLUMN_UUID + " TEXT,"
            + Child_Table.COLUMN_EB_CODE + " TEXT,"
            + Child_Table.COLUMN_HHID + " TEXT,"
            + Child_Table.COLUMN_USERNAME + " TEXT,"
            + Child_Table.COLUMN_SYSDATE + " TEXT,"
            + Child_Table.COLUMN_INDEXED + " TEXT,"
            + Child_Table.COLUMN_ISTATUS + " TEXT,"
            + Child_Table.COLUMN_DEVICEID + " TEXT,"
            + Child_Table.COLUMN_DEVICETAGID + " TEXT,"
            + Child_Table.COLUMN_SYNCED + " TEXT,"
            + Child_Table.COLUMN_SYNCED_DATE + " TEXT,"
            + Child_Table.COLUMN_APPVERSION + " TEXT,"
            + Child_Table.COLUMN_SC1 + " TEXT,"
            + Child_Table.COLUMN_SC2 + " TEXT,"
            + Child_Table.COLUMN_SC31 + " TEXT,"
            + Child_Table.COLUMN_SC32 + " TEXT,"
            + Child_Table.COLUMN_SC4 + " TEXT,"
            + Child_Table.COLUMN_SC5 + " TEXT"

            + " );"
            )


    const val SQL_CREATE_ECDINFO = ("CREATE TABLE "
            + ECDInfo_Table.TABLE_NAME + "("
            + ECDInfo_Table.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + ECDInfo_Table.COLUMN_PROJECT_NAME + " TEXT,"
            + ECDInfo_Table.COLUMN_UID + " TEXT,"
            + ECDInfo_Table.COLUMN_UUID + " TEXT,"
            + ECDInfo_Table.COLUMN_HHID + " TEXT,"
            + ECDInfo_Table.COLUMN_USERNAME + " TEXT,"
            + ECDInfo_Table.COLUMN_SYSDATE + " TEXT,"
            + ECDInfo_Table.COLUMN_INDEXED + " TEXT,"
            + ECDInfo_Table.COLUMN_ISTATUS + " TEXT,"
            + ECDInfo_Table.COLUMN_DEVICEID + " TEXT,"
            + ECDInfo_Table.COLUMN_DEVICETAGID + " TEXT,"
            + ECDInfo_Table.COLUMN_SYNCED + " TEXT,"
            + ECDInfo_Table.COLUMN_SYNCED_DATE + " TEXT,"
            + ECDInfo_Table.COLUMN_APPVERSION + " TEXT,"
            + ECDInfo_Table.COLUMN_ECDINFO + " TEXT"
            + " );"
            )


    const val SQL_CREATE_USERS = ("CREATE TABLE "
            + UsersTable.TABLE_NAME + "("
            + UsersTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + UsersTable.COLUMN_USERNAME + " TEXT,"
            + UsersTable.COLUMN_PASSWORD + " TEXT,"
            + UsersTable.COLUMN_FULLNAME + " TEXT"
            + " );"
            )


    const val SQL_CREATE_VILLAGES = ("CREATE TABLE "
            + VillagesTable.TABLE_NAME + "("
            + VillagesTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + VillagesTable.COLUMN_COUNTRY + " TEXT,"
            + VillagesTable.COLUMN_CCODE + " TEXT,"
            + VillagesTable.COLUMN_PROVINCE + " TEXT,"
            + VillagesTable.COLUMN_PROVCODE + " TEXT,"
            + VillagesTable.COLUMN_DISTRICT_NAME + " TEXT,"
            + VillagesTable.COLUMN_DCODE + " TEXT,"
            + VillagesTable.COLUMN_VILLAGE + " TEXT,"
            + VillagesTable.COLUMN_VCODE + " TEXT,"
            + VillagesTable.COLUMN_PSUCODE + " TEXT"
            + " );"
            )


    /*const val SQL_CREATE_RANDOM = ("CREATE TABLE "
            + RandomTable.TABLE_NAME + "("
            + RandomTable.COLUMN_ID + " INTEGER PRIMARY KEY,"
            + RandomTable.COLUMN_SNO + " TEXT,"
            + RandomTable.COLUMN_ENUM_BLOCK_CODE + " TEXT,"
            + RandomTable.COLUMN_HH_NO + " TEXT,"
            + RandomTable.COLUMN_HEAD_HH + " TEXT"
            + " );"
            )*/

    const val SQL_CREATE_VERSIONAPP = ("CREATE TABLE "
            + VersionTable.TABLE_NAME + " ("
            + VersionTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + VersionTable.COLUMN_VERSION_CODE + " TEXT, "
            + VersionTable.COLUMN_VERSION_NAME + " TEXT, "
            + VersionTable.COLUMN_PATH_NAME + " TEXT "
            + ");"
            )


}